# Generated by Django 3.1.1 on 2020-11-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0033_platformfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='exported',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
