# Generated by Django 3.1.1 on 2020-11-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0034_data_exported'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='data',
            index=models.Index(fields=['exported'], name='engine_data_exporte_8df759_idx'),
        ),
    ]
