# Generated by Django 3.1.1 on 2020-11-19 10:41

import cvat.apps.engine.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0035_auto_20201115_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='assignee',
            field=cvat.apps.engine.models.SafeCharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='jobcommit',
            name='author',
            field=cvat.apps.engine.models.SafeCharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='assignee',
            field=cvat.apps.engine.models.SafeCharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=cvat.apps.engine.models.SafeCharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=cvat.apps.engine.models.SafeCharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=cvat.apps.engine.models.SafeCharField(blank=True, max_length=256, null=True),
        ),
    ]
