# Generated by Django 3.1.1 on 2021-03-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0037_datasetid'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='tag',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
