apiVersion: 'serving.kubeflow.org/v1alpha2'
kind: 'InferenceService'
metadata:
  name: siammask
  namespace: kfserving-system
  annotations:
    name: SiamMask
    type: tracker
    id: siammask
    spec: ''
    framework: pytorch
    description: 'Fast Online Object Tracking and Segmentation'
  labels:
    inference: system

spec:
  default:
    predictor:
      minReplicas: 1
      custom:
        resource:
          limits:
            memory: 5G
          requests:
            cpu: 100m
        container:
          name: kfserving-container
          image: harbor.sigsus.cn:8443/sz_gongdianju/apulistech/pth.foolwood.siammask
          args: ['--model_name=siammask']
