kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: logstash
  namespace: default
spec:
  selector:
    matchLabels:
      jobmanager-node: pod
  template:
    metadata:
      name: logstash
      labels:
        jobmanager-node: pod
        app: logstash
    spec:
      nodeSelector:
        jobmanager: active
        archType: amd64
      containers:
        - name: logstash
          image: harbor.sigsus.cn:8443/library/cvat_logstash
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
              hostPort: 5001
              name: elasticsearch-port
              protocol: TCP

          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: 5001
            timeoutSeconds: 10

      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
