apiVersion: 'serving.kubeflow.org/v1alpha2'
kind: 'InferenceService'
metadata:
  name: person-reidentification-retail-0300
  namespace: kfserving-system
  annotations:
    name: Person reidentification
    type: reid
    id: person-reidentification-retail-0300
    spec: ''
    framework: openvino
    description: 'Person reidentification model for a general scenario'
  labels:
    inference: system

spec:
  default:
    predictor:
      minReplicas: 1
      custom:
        resource:
          limits:
            memory: 5G
          requests:
            cpu: 100m
        container:
          name: kfserving-container
          image: harbor.sigsus.cn:8443/sz_gongdianju/apulistech/openvino.omz.intel.person-reidentification-retail-0300
          args: ['--model_name=person-reidentification-retail-0300']
